name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '*.md'
      - LICENSE.txt

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        py:
          - "3.8"
          - "3.12"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Set up pip cache
        if: runner.os == 'Linux'
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install Hatch
        run: pipx install hatch
      - name: Check types
        run: hatch run types:check
      - name: Run lint
        run: hatch run lint:check

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.8"
          - "3.12"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
          - py: "3.9"
            os: ubuntu-latest
          - py: "3.10"
            os: ubuntu-latest
          - py: "3.11"
            os: ubuntu-latest
          - py: "3.13-dev"
            os: ubuntu-latest
          - py: "3.14-dev"
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Set up pip cache
        if: runner.os == 'Linux'
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install Hatch
        run: pipx install hatch
      - name: Run tests
        run: hatch test

  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: [test, check]
    steps:
      - run: pipx install hatch
      - name: Build dist
        run: hatch build
      - name: Publish on PyPI
        run: hatch publish
