name: CI

on:
  push:
    branches: ["main"]
    tags:
      - 'v*'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '*.md'
      - LICENSE.txt

permissions:
  contents: read

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        py:
          - "3.8"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
          cache: 'pip'
      - if: ${{ (matrix.py == '3.8') && (matrix.os == 'macos-latest') }}
        run: python -m pip install --upgrade pip
      - name: Install Hatch
        run: pipx install hatch
      - name: Check types
        run: hatch run types:check
      - name: Run lint
        run: hatch run lint:check

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.8"
          - "3.12"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
          - py: "3.9"
            os: ubuntu-latest
          - py: "3.10"
            os: ubuntu-latest
          - py: "3.11"
            os: ubuntu-latest
          - py: "3.13-dev"
            os: ubuntu-latest
          - py: "3.14-dev"
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
          cache: 'pip'
      - if: ${{ matrix.os == 'macos-latest' }}
        run: python -m pip install --upgrade pip
      - name: Install Hatch
        run: pipx install hatch
      - name: Run tests
        run: hatch test

  pypi-publish:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: [test, check]
    permissions:
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: pipx install hatch
      - name: Build dist
        run: hatch build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
