name: Python tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '*.md'
      - LICENSE.txt

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.8"
          - "3.12"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
          - py: "3.9"
            os: ubuntu-latest
          - py: "3.10"
            os: ubuntu-latest
          - py: "3.11"
            os: ubuntu-latest
          - py: "3.13.0-rc.2"
            os: ubuntu-latest
          - py: "3.14.0-alpha.0"
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Set up pip cache
        if: runner.os == 'Linux'
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install Hatch
        run: pipx install hatch
      - name: Run tests
        run: hatch test
